name: API CI
#on: [push] for monorepos
on:
  push:
    paths:
      - "./api/**"
      - ".github/workflows/api-ci.yml"

defaults:
  run:
    working-directory: ./api

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          cache: "npm"
          cache-dependency-path: ./api/package-lock.json
      - name: Install dependencies
        shell: bash
        run: npm ci
      - name: Run unit tests
        shell: bash
        run: npm run test
